
import {
  LayoutGrid,
  Users,
  Briefcase,
  FilePlus,
  ClipboardList,
  FileCheck,
  FileBarChart,
  DollarSign,
  Clock,
  CircleDollarSign,
  Landmark,
  ShieldCheck,
  BookOpen,
  FileText,
  CreditCard,
  Banknote,
  Receipt,
  FileStack,
  Mail,
  Bell,
  Database,
  User,
  Building,
  Wrench,
  Package,
  ShoppingCart,
  Truck,
  LineChart,
  FileSignature,
  FileDown,
  FileUp,
  History,
  type LucideIcon,
  Settings,
  HelpCircle,
  Book,
  Youtube,
  Ticket,
  HeartPulse,
  Palette,
  Plug,
  Wand2,
  Calculator,
  CalendarDays,
} from 'lucide-react';

export type NavLink = {
  href?: string;
  label: string;
  icon: LucideIcon;
  items?: NavLink[];
};

export const navLinks: NavLink[] = [
  {
    label: 'Dashboard',
    icon: LayoutGrid,
    href: '/dashboard',
  },
  {
    label: 'Accountant Portal',
    icon: Briefcase,
    href: '/accountant-portal',
    items: [
      { href: '/accountant-portal', label: 'Portal Dashboard', icon: LayoutGrid },
      { href: '/accountant-portal/client-list', label: 'Client List', icon: Users },
      { href: '/accountant-portal/add-new-client', label: 'Add New Client', icon: FilePlus },
      { href: '/accountant-portal/client-onboarding', label: 'Client Onboarding', icon: ClipboardList },
      { href: '/accountant-portal/task-management', label: 'Task Management', icon: FileCheck },
      { href: '/accountant-portal/document-management', label: 'Document Management', icon: FileStack },
      { href: '/accountant-portal/reporting', label: 'Reporting', icon: FileBarChart },
    ],
  },
  {
    label: 'Payroll System',
    icon: Receipt,
    href: '/payroll',
    items: [
      { href: '/payroll', label: 'Payroll Dashboard', icon: LayoutGrid },
      { href: '/payroll/employee-management', label: 'Employee Management', icon: Users },
      { href: '/payroll/time-attendance', label: 'Time & Attendance', icon: Clock },
      { href: '/payroll/payroll-processing', label: 'Payroll Processing', icon: CircleDollarSign },
      { href: '/payroll/pay-runs', label: 'Pay Runs', icon: History },
      { href: '/payroll/pay-slips', label: 'Pay Slips', icon: Receipt },
      { href: '/payroll/tax-management', label: 'Tax Management', icon: Landmark },
      { href: '/payroll/benefits-administration', label: 'Benefits Administration', icon: ShieldCheck },
      { href: '/payroll/reports', label: 'Reports', icon: FileBarChart },
      { href: '/payroll/compliance', label: 'Compliance', icon: ShieldCheck },
    ],
  },
  {
    label: 'Accounting',
    icon: BookOpen,
    href: '/accounting',
    items: [
      { href: '/accounting', label: 'Accounting Dashboard', icon: LayoutGrid },
      { href: '/accounting/chart-of-accounts', label: 'Chart of Accounts', icon: FileStack },
      { href: '/accounting/journal-entries', label: 'Journal Entries', icon: FileText },
      {
        label: 'Accounts Receivable',
        icon: CreditCard,
        href: '/accounting/accounts-receivable',
        items: [
          { href: '/accounting/accounts-receivable/dashboard', label: 'A/R Dashboard', icon: LayoutGrid },
          { href: '/accounting/accounts-receivable/customers', label: 'Customers', icon: Users },
        ],
      },
      {
        label: 'Accounts Payable',
        icon: Banknote,
        href: '/accounting/accounts-payable',
        items: [
          { href: '/accounting/accounts-payable/dashboard', label: 'A/P Dashboard', icon: LayoutGrid },
          { href: '/accounting/accounts-payable/bills', label: 'Bills', icon: Receipt },
          { href: '/accounting/accounts-payable/vendors', label: 'Vendors', icon: Users },
        ],
      },
      { href: '/accounting/general-ledger', label: 'General Ledger', icon: Book },
      { href: '/accounting/financial-statements', label: 'Financial Statements', icon: FileBarChart },
    ],
  },
  {
    label: 'Intelligent Tax',
    icon: Calculator,
    href: '/tax',
    items: [
      { href: '/tax', label: 'Tax Dashboard', icon: LayoutGrid },
      { href: '/tax/tax-planning', label: 'Tax Planning', icon: FileText },
      { href: '/tax/tax-filings', label: 'Tax Filings', icon: FileStack },
      { href: '/tax/compliance', label: 'Compliance', icon: ShieldCheck },
    ],
  },
  {
    label: 'Operations',
    icon: Wrench,
    href: '/operations',
    items: [
      { href: '/operations', label: 'Dashboard', icon: LayoutGrid },
      {
        label: 'Production',
        icon: Building,
        href: '/operations/production/work-orders',
        items: [
          { href: '/operations/production/work-orders', label: 'Work Orders', icon: FileText },
          { href: '/operations/production/scheduling', label: 'Scheduling', icon: CalendarDays },
        ],
      },
      {
        label: 'Inventory',
        icon: Package,
        href: '/operations/inventory/stock-management',
        items: [
          { href: '/operations/inventory/stock-management', label: 'Stock Management', icon: Package },
          { href: '/operations/inventory/purchase-orders', label: 'Purchase Orders', icon: ShoppingCart },
        ],
      },
      { href: '/operations/maintenance', label: 'Maintenance', icon: Wrench },
      { href: '/operations/logistics', label: 'Logistics', icon: Truck },
      { href: '/operations/analytics', label: 'Analytics', icon: LineChart },
    ],
  },
  {
    label: 'Invoicing',
    icon: Receipt,
    href: '/invoicing',
    items: [
      { href: '#', label: 'Dashboard', icon: LayoutGrid },
      { href: '#', label: 'Create Invoice', icon: FilePlus },
      { href: '#', label: 'Invoice Management', icon: FileStack },
      { href: '#', label: 'Recurring Invoices', icon: History },
      { href: '#', label: 'Estimates & Proposals', icon: FileSignature },
      { href: '#', label: 'Credit Notes', icon: FileDown },
      { href: '#', label: 'Customer Statements', icon: FileText },
      { href: '#', label: 'Reports', icon: FileBarChart },
      { href: '#', label: 'Templates & Branding', icon: Palette },
      { href: '#', label: 'Settings', icon: Settings },
    ],
  },
  {
    label: 'Banking',
    icon: Banknote,
    href: '/banking',
    items: [
      { href: '#', label: 'Dashboard', icon: LayoutGrid },
      { href: '#', label: 'Bank Connections', icon: Landmark },
      { href: '#', label: 'Review Transactions', icon: FileCheck },
      { href: '#', label: 'Reconciliation', icon: ShieldCheck },
      { href: '#', label: 'Transfers', icon: History },
      { href: '#', label: 'Transaction Rules', icon: FileText },
    ],
  },
  {
    label: 'Reports & Insights',
    icon: FileBarChart,
    href: '/insights',
  },
  {
    label: 'Communications',
    icon: Mail,
    href: '/communications',
    items: [
      { href: '#', label: 'Email Center', icon: Mail },
      { href: '#', label: 'Notifications', icon: Bell },
      { href: '#', label: 'Templates', icon: FileStack },
      { href: '#', label: 'Automation', icon: Wrench },
    ],
  },
  {
    label: 'Data Management',
    icon: Database,
    href: '/data',
    items: [
      { href: '#', label: 'Data Dashboard', icon: LayoutGrid },
      { href: '#', label: 'Data Import', icon: FileDown },
      { href: '#', label: 'Data Export', icon: FileUp },
      { href: '#', label: 'Backup & Restore', icon: History },
    ],
  },
  {
    label: 'User',
    icon: User,
    href: '/settings',
  },
  {
    label: 'Settings',
    icon: Settings,
    href: '/settings',
    items: [
      { href: '/settings', label: 'Profile', icon: User },
      { href: '#', label: 'Company Settings', icon: Building },
      { href: '#', label: 'Team Management', icon: Users },
      { href: '#', label: 'Security', icon: ShieldCheck },
      { href: '#', label: 'Integrations', icon: Plug },
      { href: '#', label: 'Billing & Subscription', icon: CreditCard },
      { href: '#', label: 'Appearance', icon: Palette },
      { href: '#', label: 'Payroll Wizard', icon: Wand2 },
    ],
  },
  {
    label: 'Help',
    icon: HelpCircle,
    href: '/help',
    items: [
      { href: '#', label: 'Help Center', icon: HelpCircle },
      { href: '#', label: 'Knowledge Base', icon: Book },
      { href: '#', label: 'Video Tutorials', icon: Youtube },
      { href: '#', label: 'Support Tickets', icon: Ticket },
      { href: '#', label: 'System Status', icon: HeartPulse },
    ],
  },
];
