
import {
  LayoutGrid,
  Users,
  Briefcase,
  FilePlus,
  ClipboardList,
  FileCheck,
  FileBarChart,
  DollarSign,
  Clock,
  CircleDollarSign,
  Landmark,
  ShieldCheck,
  BookOpen,
  FileText,
  CreditCard,
  Receipt,
  FileStack,
  Mail,
  Bell,
  Database,
  User,
  Building,
  Wrench,
  Package,
  ShoppingCart,
  Truck,
  LineChart,
  FileSignature,
  FileDown,
  FileUp,
  History,
  type LucideIcon,
  Settings,
  HelpCircle,
  Book,
  Youtube,
  Ticket,
  HeartPulse,
  Palette,
  Plug,
  Wand2,
  Calculator,
  CalendarDays,
  BarChart4,
  Link as LinkIcon,
  RefreshCw,
  ArrowLeftRight,
  PieChart,
  SlidersHorizontal,
  Zap,
  CalendarClock,
  MessageSquare,
  LifeBuoy,
  Rocket,
  BookUser,
  Phone,
  GraduationCap,
  Info,
  PersonStanding,
  Scale,
  Keyboard,
  Languages,
  AlertTriangle,
  Timer,
  ListChecks,
  FileBarChart2,
  TrendingUp,
  Search,
  FolderOpen,
  MapPin,
  BarChart3,
  Pencil,
  Banknote,
} from 'lucide-react';

export type NavLink = {
  href?: string;
  label: string;
  icon: LucideIcon;
  items?: NavLink[];
  onboardingId?: string;
  allowedRoles?: string[]; // 'Admin' or 'User'
};

export const navLinks: NavLink[] = [
  {
    label: 'Dashboard',
    icon: LayoutGrid,
    href: '/dashboard',
    allowedRoles: ['Admin', 'User'],
  },
  {
    label: 'Accountant Portal',
    icon: Briefcase,
    href: '/accountant-portal',
    allowedRoles: ['Admin'],
    items: [
      { href: '/accountant-portal', label: 'Portal Dashboard', icon: LayoutGrid },
      { href: '/accountant-portal/client-list', label: 'Client List', icon: Users },
      { href: '/accountant-portal/add-new-client', label: 'Add New Client', icon: FilePlus },
      { href: '/accountant-portal/client-onboarding', label: 'Client Onboarding', icon: ClipboardList },
      { href: '/accountant-portal/task-management', label: 'Task Management', icon: FileCheck },
      { href: '/accountant-portal/document-management', label: 'Document Management', icon: FileStack },
      { href: '/accountant-portal/reporting', label: 'Reporting', icon: FileBarChart },
    ],
  },
  {
    label: 'Invoicing',
    icon: Receipt,
    href: '/invoicing/dashboard',
    onboardingId: 'invoicing-link',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/invoicing/dashboard', label: 'Dashboard', icon: LayoutGrid },
      { href: '/invoicing/new', label: 'Create Invoice', icon: FilePlus },
      { href: '/invoicing/invoices', label: 'Invoice Management', icon: FileStack },
      { href: '/invoicing/recurring', label: 'Recurring Invoices', icon: History },
      { href: '/invoicing/estimates', label: 'Estimates & Proposals', icon: FileSignature },
      { href: '/invoicing/credit-notes', label: 'Credit Notes', icon: FileDown },
      { href: '/invoicing/statements', label: 'Customer Statements', icon: FileText },
      {
        label: 'Reports',
        icon: FileBarChart,
        href: '/invoicing/reports',
        items: [
          { href: '/invoicing/reports/ar-aging', label: 'A/R Aging', icon: FileText },
          { href: '/invoicing/reports/sales-by-customer', label: 'Sales by Customer', icon: Users },
          { href: '/invoicing/reports/sales-by-item', label: 'Sales by Item', icon: PieChart },
          { href: '/invoicing/reports/tax-summary', label: 'Sales Tax Summary', icon: FileBarChart2 },
        ],
      },
      { href: '/invoicing/templates', label: 'Templates & Branding', icon: Palette },
      { href: '/invoicing/settings', label: 'Settings', icon: Settings },
    ],
  },
  {
    label: 'Accounting',
    icon: BookOpen,
    href: '/accounting',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/accounting', label: 'Accounting Dashboard', icon: LayoutGrid },
      { href: '/accounting/chart-of-accounts', label: 'Chart of Accounts', icon: FileStack, onboardingId: 'chart-of-accounts-link' },
      { href: '/accounting/journal-entries', label: 'Journal Entries', icon: FileText, onboardingId: 'journal-entries-link' },
      {
        label: 'Accounts Receivable',
        icon: CreditCard,
        href: '/accounting/accounts-receivable',
        items: [
          { href: '/accounting/accounts-receivable/dashboard', label: 'A/R Dashboard', icon: LayoutGrid },
          { href: '/accounting/accounts-receivable/customers', label: 'Customers', icon: Users },
        ],
      },
      {
        label: 'Accounts Payable',
        icon: Banknote,
        href: '/accounting/accounts-payable',
        items: [
          { href: '/accounting/accounts-payable/dashboard', label: 'A/P Dashboard', icon: LayoutGrid },
          { href: '/accounting/accounts-payable/bills', label: 'Bills', icon: Receipt },
          { href: '/accounting/accounts-payable/vendors', label: 'Vendors', icon: Users },
        ],
      },
      { href: '/accounting/general-ledger', label: 'General Ledger', icon: Book },
      {
        label: 'Financial Statements',
        icon: FileBarChart,
        href: '/accounting/financial-statements',
        items: [
          { href: '/accounting/financial-statements', label: 'Statements Hub', icon: LayoutGrid },
          { href: '/accounting/financial-statements/profit-and-loss', label: 'Profit & Loss', icon: FileText },
          { href: '/accounting/financial-statements/consolidated-pl', label: 'Consolidated P&L', icon: FileBarChart2 },
          { href: '/accounting/financial-statements/balance-sheet', label: 'Balance Sheet', icon: FileText },
          { href: '/accounting/financial-statements/cash-flow', label: 'Cash Flow', icon: FileText },
        ],
      },
       {
        label: 'Period-End Close',
        icon: Clock,
        href: '/accounting/periods/close',
        items: [
            { href: '/accounting/periods/close', label: 'Close Period', icon: Clock },
            { href: '/accounting/periods/reopen', label: 'Reopen Period', icon: RefreshCw },
        ]
       }
    ],
  },
  {
    label: 'Banking',
    icon: Landmark,
    href: '/banking',
    onboardingId: 'banking-link',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/banking/dashboard', label: 'Dashboard', icon: LayoutGrid },
      { href: '/banking/accounts', label: 'Accounts', icon: Banknote },
      { href: '/banking/connections', label: 'Bank Connections', icon: LinkIcon },
      { href: '/banking/review-transactions', label: 'Review Transactions', icon: FileCheck },
      { href: '/banking/reconciliation', label: 'Reconciliation', icon: RefreshCw, onboardingId: 'bank-reconciliation-link' },
      { href: '/banking/transfers', label: 'Transfers', icon: ArrowLeftRight },
      { href: '/banking/rules', label: 'Transaction Rules', icon: FileText },
    ],
  },
  {
    label: 'Operations',
    icon: Wrench,
    href: '/operations',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/operations', label: 'Dashboard', icon: LayoutGrid },
      {
        label: 'Job Costing',
        icon: CircleDollarSign,
        href: '/operations/job-costing/dashboard',
        items: [
           { href: '/operations/job-costing/dashboard', label: 'Dashboard', icon: LayoutGrid },
           { href: '/operations/job-costing/jobs', label: 'All Jobs', icon: Briefcase },
           { href: '/operations/job-costing/enter-bill', label: 'Enter Bill', icon: Receipt },
           { 
             href: '/operations/job-costing/reports', 
             label: 'Reports', 
             icon: FileBarChart,
             items: [
                { href: '/operations/job-costing/reports/profitability', label: 'Profitability Report', icon: BarChart3 },
                { href: '/operations/job-costing/reports/budget-vs-actual', label: 'Budget vs. Actual', icon: FileBarChart2 },
                { href: '/operations/job-costing/reports/wip', label: 'WIP Report', icon: Users },
             ]
           },
        ]
      },
      {
        label: 'Production',
        icon: Building,
        href: '/operations/production/plans',
        items: [
          { href: '/operations/production/plans', label: 'Planning', icon: FileText },
          { href: '/operations/production/scheduling', label: 'Scheduling', icon: CalendarDays },
          { href: '/operations/production/tracking', label: 'Tracking', icon: BarChart4 },
          { href: '/operations/production/work-orders', label: 'Work Orders', icon: ClipboardList },
        ],
      },
      {
        label: 'Inventory',
        icon: Package,
        href: '/operations/inventory/stock-management',
        items: [
          { href: '/operations/inventory/stock-management', label: 'Stock Management', icon: Package },
          { href: '/operations/inventory/purchase-orders', label: 'Purchase Orders', icon: ShoppingCart },
          { href: '/operations/inventory/adjust-stock', label: 'Stock Adjustments', icon: Pencil },
        ],
      },
      { href: '/operations/maintenance', label: 'Maintenance', icon: Wrench },
      { href: '/operations/logistics', label: 'Logistics', icon: Truck },
      { href: '/operations/analytics', label: 'Analytics', icon: LineChart },
    ],
  },
  {
    label: 'Payroll System',
    icon: CircleDollarSign,
    href: '/payroll',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/payroll', label: 'Payroll Dashboard', icon: LayoutGrid },
      { href: '/payroll/employee-management', label: 'Employee Management', icon: Users },
      { href: '/payroll/time-attendance', label: 'Time & Attendance', icon: Clock },
      { href: '/payroll/payroll-processing', label: 'Payroll Processing', icon: Zap },
      { href: '/payroll/pay-runs', label: 'Pay Runs', icon: History },
      { href: '/payroll/pay-slips', label: 'Pay Slips', icon: Receipt },
      { href: '/payroll/tax-management', label: 'Tax Management', icon: Landmark },
      { href: '/payroll/benefits-administration', label: 'Benefits Administration', icon: ShieldCheck },
      { href: '/payroll/reports', label: 'Reports', icon: FileBarChart },
      { href: '/payroll/compliance', label: 'Compliance', icon: ShieldCheck },
    ],
  },
  {
    label: 'Client Management',
    icon: Users,
    href: '/client-management/billing',
    allowedRoles: ['Admin'],
    items: [
        { href: '/client-management/billing', label: 'Billing', icon: CreditCard },
        { href: '/client-management/invoicing/batch', label: 'Batch Invoicing', icon: Mail },
        { href: '/payments/process', label: 'Process Payments', icon: CreditCard },
        { href: '/compliance/clients', label: 'Client Compliance', icon: ShieldCheck },
    ],
  },
  {
    label: 'Investments',
    icon: TrendingUp,
    href: '/portfolio',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/portfolio/overview', label: 'Portfolio Overview', icon: LayoutGrid },
      { href: '/portfolio/asset-classes', label: 'Asset Classes', icon: PieChart },
      { href: '/trading', label: 'Paper Trading', icon: LineChart },
      { href: '/search', label: 'Stock Search', icon: Search },
      { href: '/learn', label: 'Learn', icon: GraduationCap },
    ],
  },
  {
    label: 'Intelligent Tax',
    icon: Calculator,
    href: '/tax',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/tax', label: 'Tax Dashboard', icon: LayoutGrid },
      { href: '/tax/tax-planning', label: 'Tax Planning', icon: FileText },
      { href: '/tax/tax-filings', label: 'Tax Filings', icon: FileStack },
      { href: '/tax/compliance', label: 'Compliance', icon: ShieldCheck },
    ],
  },
  {
    label: 'Reports & Insights',
    icon: BarChart4,
    href: '/reports-insights/dashboard',
    onboardingId: 'reports-link',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/reports-insights/dashboard', label: 'Dashboard', icon: LayoutGrid },
      { href: '/reports-insights/financial-reports', label: 'Financial Reports', icon: FileBarChart, onboardingId: 'financial-reports-link' },
      { href: '/reports-insights/sales-analytics', label: 'Sales Analytics', icon: LineChart },
      { href: '/reports-insights/expense-analytics', label: 'Expense Analytics', icon: PieChart },
      { href: '/reports-insights/summarization-tools', label: 'AI Summarization', icon: Wand2 },
      { href: '/reports-insights/builder', label: 'Report Builder', icon: SlidersHorizontal },
      { href: '/reports-insights/forecasting', label: 'Forecasting', icon: Zap },
      { href: '/reports-insights/scheduled-reports', label: 'Scheduled Reports', icon: CalendarClock },
    ],
  },
  {
    label: 'Projects',
    icon: Briefcase,
    href: '/projects',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/projects/dashboard', label: 'Projects Dashboard', icon: LayoutGrid },
      { href: '/projects/all-projects', label: 'All Projects', icon: ListChecks },
      { href: '/projects/time-tracking', label: 'Time Tracking', icon: Timer },
      { href: '/projects/project-reports', label: 'Reports', icon: FileBarChart },
    ],
  },
  {
    label: 'Communications',
    icon: MessageSquare,
    href: '/communications',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/communications/email-center', label: 'Email Center', icon: Mail },
      { href: '/communications/notifications', label: 'Notifications', icon: Bell },
      { href: '/communications/templates', label: 'Templates', icon: FileText },
      { href: '/communications/automation', label: 'Automation', icon: Wrench },
    ],
  },
  {
    label: 'Asset Management',
    icon: FolderOpen,
    href: '/asset-management',
    allowedRoles: ['Admin', 'User'],
    items: [
        { href: '/asset-management/locations', label: 'Asset Locations', icon: MapPin },
    ]
  },
  {
    label: 'Data Management',
    icon: Database,
    href: '/data-management',
    allowedRoles: ['Admin'],
    items: [
      { href: '/data-management', label: 'Dashboard', icon: LayoutGrid },
      { href: '/data-management/data-import', label: 'Data Import', icon: FileDown },
      { href: '/data-management/data-export', label: 'Data Export', icon: FileUp },
      { href: '/data-management/backup-restore', label: 'Backup & Restore', icon: History },
      { href: '/reports/validation', label: 'Validation Reports', icon: FileCheck },
    ],
  },
  {
    label: 'Settings',
    icon: Settings,
    href: '/settings',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/settings', label: 'Account', icon: User },
      { href: '/settings/company', label: 'Company', icon: Building },
      { href: '/settings/team', label: 'Team Management', icon: Users, onboardingId: 'team-settings-link' },
      { href: '/settings/security', label: 'Security', icon: ShieldCheck },
      { href: '/settings/integrations', label: 'Integrations', icon: Plug },
      { href: '/settings/billing', label: 'Billing & Subscription', icon: CreditCard },
      { href: '/settings/appearance', label: 'Appearance', icon: Palette },
      { href: '/settings/payroll-wizard', label: 'Payroll Wizard', icon: Wand2 },
      { href: '/settings/onboarding', label: 'Onboarding', icon: Rocket },
      { href: '/settings/data-management', label: 'Data Management', icon: Database },
    ],
  },
  {
    label: 'Help',
    icon: HelpCircle,
    href: '/help',
    allowedRoles: ['Admin', 'User'],
    items: [
      { href: '/help', label: 'Help Center', icon: LifeBuoy },
      { href: '/help/getting-started', label: 'Getting Started', icon: Rocket },
      { href: '/help/user-guides', label: 'User Guides', icon: BookUser },
      { href: '/help/troubleshooting', label: 'Troubleshooting', icon: Wrench },
      { href: '/help/contact-support', label: 'Contact Support', icon: Phone },
      { href: '/help/training', label: 'Training', icon: GraduationCap },
      { href: '/help/community', label: 'Community', icon: Users },
      { href: '/help/system-information', label: 'System Information', icon: Info },
      { href: '/help/accessibility', label: 'Accessibility', icon: PersonStanding },
      { href: '/help/feedback', label: 'Feedback', icon: MessageSquare },
      { href: '/help/legal', label: 'Legal', icon: Scale },
      { href: '/help/keyboard-shortcuts', label: 'Keyboard Shortcuts', icon: Keyboard },
      { href: '/help/language-region', label: 'Language & Region', icon: Languages },
      { href: '/help/updates-maintenance', label: 'Updates & Maintenance', icon: RefreshCw },
      { href: '/help/emergency-assistance', label: 'Emergency Assistance', icon: AlertTriangle },
    ],
  },
];
